### ISSUE TITLE
 environment configuration 

### ISSUE THREAD

**Issue by findscripter** [yumouwei/super-mario-bros-reinforcement-learning#2]
Why can't I run this project with the exact same environment configuration as you?
![屏幕截图 2024-06-29 225020](https://github.com/user-attachments/assets/a627dbbc-9102-45cd-85f6-e6dc8b538b9b)
![1861572E1CC2DA1E8062359F81488CC6](https://github.com/user-attachments/assets/ed19e05d-f7cf-48a1-ae0b-cbe8201316df)

**Comment by yumouwei** [comment]
That looks like a `gym-super-mario-bros` problem. I'd recommend to take a look at https://github.com/Kautenja/gym-super-mario-bros and post a issue there.

**Comment by findscripter** [comment]
How long does it take for this model to be pre-trained and formally trained? My GPU is an RTX4060.

**Comment by yumouwei** [comment]
It took me a couple of hours on a laptop. For yours you need to give it a try yourself.

**Comment by findscripter** [comment]
![0b939069-4ea5-4e2a-9c19-0cc5944bba47](https://github.com/user-attachments/assets/da4bbde8-c3b5-4151-bfc8-13cebd9aadac)
Why is it that after a day's training the code is still running and the left side of the picture shows that a model has been generated

**Comment by findscripter** [comment]
![28f16e78-2486-4bde-b78b-23b969e16e09](https://github.com/user-attachments/assets/500b976a-3cc9-4877-bf9e-ffd36fd15a69)

![0b939069-4ea5-4e2a-9c19-0cc5944bba47](https://github.com/user-attachments/assets/117da1d2-95e4-45cf-a718-4dae96550e2b)
Why is it that after a day's training the code is still running and the left side of the picture shows that a model has been generated
